# This is a YAML file.
# Please use two-space tabs instead of the \t character.

server:
  bind: "127.0.0.1"
  port: "60001"
  type: "fastcgi"       # Types are "fastcgi" for a FastCGI server and "standalone" for a simple HTTP server.

hosts:
  default: "./site"

