## Tango!
##
## App configuration
##

## Here we set options for the server.
server:
  type: fastcgi       # Type of server to spawn. "fastcgi" or "standalone".
  bind: 127.0.0.1     # Listen on all interfaces.
  port: 60002         # Listen on port 9292.
